server:
  port: 8000

spring:
  application:
    name: gateway
  config:
    import: "optional:consul:"
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    consul:
      enabled: true
      discovery:
        query-passing: true
      config:
        data-key: application.yml
        prefix: config
        format: yaml
        default-context: defaults
    gateway:
      routes:
        - id: FoodFetcher
          uri: http://localhost:8081
          predicates:
            - Path=/api/food/**
        - id: emailservice
          uri: lb://emailservice
          predicates:
            - Path=/api/email/**
        - id: RecipeService
          uri: http://localhost:8080
          predicates:
            - Path=/api/recipe/**
          filters:
            - StripPrefix=0
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:3000"
            allowed-headers:
              - "*"
            allowed-methods:
              - "GET"
              - "POST"
              - "OPTIONS"
            allow-credentials: true