services:

  frontend:
    image: mcflonilo/mikrotjenestereksamen:frontend
    ports:
      - '3000:80'

  emailservice:
    image: mcflonilo/mikrotjenestereksamen:emailservice
    ports:
      - '8083:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONSUL_HOST=consul
    depends_on:
      - consul-importer
      - rabbitmq-dev
    networks:
      - micro_food

  foodfetcher:
    image: mcflonilo/mikrotjenestereksamen:foodfetcher
    ports:
      - '8081:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONSUL_HOST=consul-dev
    depends_on:
      - consul-dev
      - rabbitmq-dev
    networks:
      - micro_food

  shoppinglist:
    image: mcflonilo/mikrotjenestereksamen:shoppinglistservice
    ports:
      - '8082:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONSUL_HOST=consul-dev
    depends_on:
      - consul-dev
      - rabbitmq-dev
    networks:
      - micro_food

  recipeservice:
    image: mcflonilo/mikrotjenestereksamen:recipeservice
    ports:
      - '8084:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONSUL_HOST=consul
    depends_on:
      - consul-importer
      - rabbitmq-dev
    networks:
      - micro_food

  gateway:
    image: mcflonilo/mikrotjenestereksamen:gateway
    ports:
      - '8000:8000'
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONSUL_HOST=consul
    depends_on:
      - rabbitmq-dev
      - consul-importer
    networks:
      - micro_food

  loginservice:
    image: mcflonilo/mikrotjenestereksamen:loginservice
    ports:
      - '8080:8000'
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONSUL_HOST=consul
    depends_on:
      - rabbitmq-dev
      - consul-importer
    networks:
      - micro_food

  consul-dev:
    image: hashicorp/consul:1.19.2
    container_name: consul
    ports:
      - '8500:8500'
      - '8600:8600/udp'
    command: 'agent -dev -node=cards -client=0.0.0.0 -log-level=INFO'
    networks:
      - micro_food

  consul-importer:
    image: consul-importer:1.19.2
    depends_on:
      - consul-dev
    networks:
      - micro_food

  rabbitmq-dev:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - micro_food

networks:
  micro_food:
    driver: bridge