name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/frontend:latest

      - name: Build and push gateway image
        uses: docker/build-push-action@v4
        with:
          context: ./gateway
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/gateway:latest

      - name: Build and push loginservice image
        uses: docker/build-push-action@v4
        with:
          context: ./LoginService
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/loginservice:latest

      - name: Build and push shoppinglistservice image
        uses: docker/build-push-action@v4
        with:
          context: ./ShoppingListService
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/shoppinglistservice:latest

      - name: Build and push recipeservice image
        uses: docker/build-push-action@v4
        with:
          context: ./RecipeService
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/recipeservice:latest