name: Build and Push Docker Images

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push frontend service
        with:
          context: ./frontend
        run: |
          docker build -t mcflonilo/mikrotjenestereksamen:frontend .
          docker push mcflonilo/mikrotjenestereksamen:frontend

      - name: Build and push emailservice
        with:
          context: ./EmailService
        run: |
          docker build -t mcflonilo/mikrotjenestereksamen:emailservice .
          docker push mcflonilo/mikrotjenestereksamen:emailservice

      - name: Build and push FoodFetcher
        with:
          context: ./FoodFetcher
        run: |
          docker build -t mcflonilo/mikrotjenestereksamen:foodfetcher .
          docker push mcflonilo/mikrotjenestereksamen:foodfetcher

      - name: Build and push Gateway
        with:
          context: ./Gateway
        run: |
          docker build -t mcflonilo/mikrotjenestereksamen:gateway .
          docker push mcflonilo/mikrotjenestereksamen:gateway

      - name: Build and push LoginService
        with:
          context: ./LoginService
        run: |
          docker build -t mcflonilo/mikrotjenestereksamen:loginservice .
          docker push mcflonilo/mikrotjenestereksamen:loginservice

      - name: Build and push RecipeService
        with:
          context: ./RecipeService
        run: |
          docker build -t mcflonilo/mikrotjenestereksamen:recipeservice .
          docker push mcflonilo/mikrotjenestereksamen:recipeservice

      - name: Build and push ShoppingListService
        with:
          context: ./ShoppingListService
        run: |
          docker build -t mcflonilo/mikrotjenestereksamen:shoppinglistService .
          docker push mcflonilo/mikrotjenestereksamen:shoppinglistService