on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Check which directories have changes
        id: check_changes
        run: |
          echo "::set-output name=frontend::$(git diff --name-only HEAD^ HEAD | grep '^frontend/' || echo 'false')"
          echo "::set-output name=emailservice::$(git diff --name-only HEAD^ HEAD | grep '^EmailService/' || echo 'false')"
          echo "::set-output name=foodfetcher::$(git diff --name-only HEAD^ HEAD | grep '^FoodFetcher/' || echo 'false')"
          echo "::set-output name=gateway::$(git diff --name-only HEAD^ HEAD | grep '^Gateway/' || echo 'false')"
          echo "::set-output name=loginservice::$(git diff --name-only HEAD^ HEAD | grep '^LoginService/' || echo 'false')"
          echo "::set-output name=recipeservice::$(git diff --name-only HEAD^ HEAD | grep '^RecipeService/' || echo 'false')"
          echo "::set-output name=shoppinglistservice::$(git diff --name-only HEAD^ HEAD | grep '^ShoppingListService/' || echo 'false')"


      - name: Build frontend
        run: |
          cd ./frontend
          npm install
          npm run build

      - name: Build and push frontend service
        if: ${{ contains(github.event.head_commit.message, 'frontend') || steps.check_changes.outputs.frontend == 'true' }}
        run: |
          docker build -t mcflonilo/mikrotjenestereksamen:frontend ./frontend
          docker push mcflonilo/mikrotjenestereksamen:frontend

      - name: Build and push email service
        if: ${{ steps.check_changes.outputs.emailservice == 'true' }}
        run: |
          docker build -t mcflonilo/mikrotjenestereksamen:emailservice ./EmailService
          docker push mcflonilo/mikrotjenestereksamen:emailservice

      - name: Build and push food fetcher
        if: ${{ steps.check_changes.outputs.foodfetcher == 'true' }}
        run: |
          docker build -t mcflonilo/mikrotjenestereksamen:foodfetcher ./FoodFetcher
          docker push mcflonilo/mikrotjenestereksamen:foodfetcher

      - name: Build and push gateway
        if: ${{ steps.check_changes.outputs.gateway == 'true' }}
        run: |
          docker build -t mcflonilo/mikrotjenestereksamen:gateway ./Gateway
          docker push mcflonilo/mikrotjenestereksamen:gateway

      - name: Build and push login service
        if: ${{ steps.check_changes.outputs.loginservice == 'true' }}
        run: |
          docker build -t mcflonilo/mikrotjenestereksamen:loginservice ./LoginService
          docker push mcflonilo/mikrotjenestereksamen:loginservice

      - name: Build and push recipe service
        if: ${{ steps.check_changes.outputs.recipeservice == 'true' }}
        run: |
          docker build -t mcflonilo/mikrotjenestereksamen:recipeservice ./RecipeService
          docker push mcflonilo/mikrotjenestereksamen:recipeservice

      - name: Build and push shopping list service
        if: ${{ steps.check_changes.outputs.shoppinglistservice == 'true' }}
        run: |
          docker build -t mcflonilo/mikrotjenestereksamen:shoppinglistservice ./ShoppingListService
          docker push mcflonilo/mikrotjenestereksamen:shoppinglistservice

